# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cryptocurrency app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cryptocurrency app
  pod "SwiftChart"

  target 'cryptocurrency appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cryptocurrency appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
